=== nikibeep/webcode/bloge.dtd
<!ELEMENT catalog (cd+)>
<!ELEMENT cd (user_id,users,password,email_id,article_type,status)>
<!ELEMENT user_id (#PCDATA)>
<!ELEMENT users (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT email_id (#PCDATA)>
<!ELEMENT article_type (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== nikibeep/webcode/bloge.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="E:\webcode\blogx.xsl"?>
<?xml-model href="bloge.xsd"?>
<!DOCTYPE catalog SYSTEM "bloge.dtd">
<catalog>
  <cd>
    <user_id>001</user_id>
    <users>Nikhil</users>
    <password>12332</password>
    <email_id>nikil@gmail.com</email_id>
  </cd>

  <cd>
    <user_id>002</user_id>
    <users>Melvin</users>
    <password>12123</password>
    <email_id>melvin@gmail.com</email_id>
  </cd>

  <cd>
    <user_id>003</user_id>
    <users>Arpith</users>
    <password>12313</password>
    <email_id>arpith@gmail.com</email_id>
  </cd>

  <cd>
    <user_id>004</user_id>
    <users>pradeep</users>
    <password>12313</password>
    <email_id>pradeep@gmail.com</email_id>
  </cd>

  <cd>
    <user_id>005</user_id>
    <users>Aaryan</users>
    <password>13191</password>
    <email_id>aaryan@gamil.com</email_id>
  </cd>

  <cd>
    <user_id>006</user_id>
    <users>Melon</users>
    <password>23232</password>
    <email_id>melon@gmail.com</email_id>
  </cd>

</catalog>
